CREATE TABLE IF NOT EXISTS nature_of_suit_codes (
    code TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

-- Seed all real JS-44 NOS codes
INSERT INTO nature_of_suit_codes (code, title, category) VALUES
-- Contract
('110', 'Insurance', 'Contract'),
('120', 'Marine', 'Contract'),
('130', 'Miller Act', 'Contract'),
('140', 'Negotiable Instrument', 'Contract'),
('150', 'Recovery of Overpayment', 'Contract'),
('151', 'Medicare Act', 'Contract'),
('152', 'Recovery of Defaulted Student Loans', 'Contract'),
('153', 'Recovery of Overpayment of Veteran''s Benefits', 'Contract'),
('160', 'Stockholders'' Suits', 'Contract'),
('190', 'Other Contract', 'Contract'),
('195', 'Contract Product Liability', 'Contract'),
('196', 'Franchise', 'Contract'),
-- Real Property
('210', 'Land Condemnation', 'Real Property'),
('220', 'Foreclosure', 'Real Property'),
('230', 'Rent Lease & Ejectment', 'Real Property'),
('240', 'Torts to Land', 'Real Property'),
('245', 'Tort Product Liability', 'Real Property'),
('290', 'All Other Real Property', 'Real Property'),
-- Torts - Personal Injury
('310', 'Airplane', 'Torts - Personal Injury'),
('315', 'Airplane Product Liability', 'Torts - Personal Injury'),
('320', 'Assault Libel & Slander', 'Torts - Personal Injury'),
('330', 'Federal Employers'' Liability', 'Torts - Personal Injury'),
('340', 'Marine', 'Torts - Personal Injury'),
('345', 'Marine Product Liability', 'Torts - Personal Injury'),
('350', 'Motor Vehicle', 'Torts - Personal Injury'),
('355', 'Motor Vehicle Product Liability', 'Torts - Personal Injury'),
('360', 'Other Personal Injury', 'Torts - Personal Injury'),
('362', 'Personal Injury - Medical Malpractice', 'Torts - Personal Injury'),
('365', 'Personal Injury - Product Liability', 'Torts - Personal Injury'),
('367', 'Health Care/Pharmaceutical PI/PL', 'Torts - Personal Injury'),
('368', 'Asbestos Personal Injury Product Liability', 'Torts - Personal Injury'),
-- Torts - Personal Property
('370', 'Other Fraud', 'Torts - Personal Property'),
('371', 'Truth in Lending', 'Torts - Personal Property'),
('380', 'Other Personal Property Damage', 'Torts - Personal Property'),
('385', 'Property Damage Product Liability', 'Torts - Personal Property'),
-- Civil Rights
('440', 'Other Civil Rights', 'Civil Rights'),
('441', 'Voting', 'Civil Rights'),
('442', 'Employment', 'Civil Rights'),
('443', 'Housing/Accommodations', 'Civil Rights'),
('444', 'Welfare', 'Civil Rights'),
('445', 'ADA - Employment', 'Civil Rights'),
('446', 'ADA - Other', 'Civil Rights'),
('448', 'Education', 'Civil Rights'),
-- Prisoner Petitions
('510', 'Motions to Vacate Sentence', 'Prisoner Petitions'),
('530', 'General', 'Prisoner Petitions'),
('535', 'Death Penalty', 'Prisoner Petitions'),
('540', 'Mandamus & Other', 'Prisoner Petitions'),
('550', 'Civil Rights', 'Prisoner Petitions'),
('555', 'Prison Condition', 'Prisoner Petitions'),
('560', 'Civil Detainee', 'Prisoner Petitions'),
-- Forfeiture/Penalty
('610', 'Agriculture', 'Forfeiture/Penalty'),
('620', 'Other Food & Drug', 'Forfeiture/Penalty'),
('625', 'Drug Related Seizure of Property', 'Forfeiture/Penalty'),
('630', 'Liquor Laws', 'Forfeiture/Penalty'),
('640', 'RR & Truck', 'Forfeiture/Penalty'),
('650', 'Airline Regs.', 'Forfeiture/Penalty'),
('660', 'Occupational Safety/Health', 'Forfeiture/Penalty'),
('690', 'Other', 'Forfeiture/Penalty'),
-- Labor
('710', 'Fair Labor Standards Act', 'Labor'),
('720', 'Labor/Management Relations', 'Labor'),
('730', 'Labor/Mgmt. Reporting & Disclosure Act', 'Labor'),
('740', 'Railway Labor Act', 'Labor'),
('751', 'Family and Medical Leave Act', 'Labor'),
('790', 'Other Labor Litigation', 'Labor'),
('791', 'Employee Retirement Income Security Act', 'Labor'),
-- Property Rights
('820', 'Copyrights', 'Property Rights'),
('830', 'Patent', 'Property Rights'),
('835', 'Patent - Abbreviated New Drug Application', 'Property Rights'),
('840', 'Trademark', 'Property Rights'),
('880', 'Defend Trade Secrets Act', 'Property Rights'),
-- Bankruptcy
('422', 'Appeal 28 USC 158', 'Bankruptcy'),
('423', 'Withdrawal 28 USC 157', 'Bankruptcy'),
-- Social Security
('861', 'HIA (1395ff)', 'Social Security'),
('862', 'Black Lung (923)', 'Social Security'),
('863', 'DIWC/DIWW (405(g))', 'Social Security'),
('864', 'SSID Title XVI', 'Social Security'),
('865', 'RSI (405(g))', 'Social Security'),
-- Federal Tax Suits
('870', 'Taxes (US Plaintiff or Defendant)', 'Federal Tax Suits'),
('871', 'IRS - Third Party 26 USC 7609', 'Federal Tax Suits'),
-- Other Statutes
('375', 'False Claims Act', 'Other Statutes'),
('376', 'Qui Tam (31 USC 3729(a))', 'Other Statutes'),
('400', 'State Reapportionment', 'Other Statutes'),
('410', 'Antitrust', 'Other Statutes'),
('430', 'Banks and Banking', 'Other Statutes'),
('450', 'Commerce', 'Other Statutes'),
('460', 'Deportation', 'Other Statutes'),
('462', 'Naturalization Application', 'Other Statutes'),
('463', 'Habeas Corpus - Alien Detainee', 'Other Statutes'),
('465', 'Other Immigration Actions', 'Other Statutes'),
('470', 'Racketeer Influenced and Corrupt Organizations', 'Other Statutes'),
('480', 'Consumer Credit', 'Other Statutes'),
('485', 'Telephone Consumer Protection Act', 'Other Statutes'),
('490', 'Cable/Sat TV', 'Other Statutes'),
('491', 'Securities/Commodities/Exchange', 'Other Statutes'),
('893', 'Environmental Matters', 'Other Statutes'),
('895', 'Freedom of Information Act', 'Other Statutes'),
('896', 'Arbitration', 'Other Statutes'),
('899', 'Administrative Procedure Act/Review of Agency Decision', 'Other Statutes'),
('950', 'Constitutionality of State Statutes', 'Other Statutes')
ON CONFLICT (code) DO NOTHING;
