#[cfg(feature = "server")]
pub mod attorney;
#[cfg(feature = "server")]
pub mod calendar;
#[cfg(feature = "server")]
pub mod case;
#[cfg(feature = "server")]
pub mod civil_case;
#[cfg(feature = "server")]
pub mod deadline;
#[cfg(feature = "server")]
pub mod docket;
#[cfg(feature = "server")]
pub mod attachment;
#[cfg(feature = "server")]
pub mod document;
#[cfg(feature = "server")]
pub mod document_event;
#[cfg(feature = "server")]
pub mod event;
#[cfg(feature = "server")]
pub mod judge;
#[cfg(feature = "server")]
pub mod party;
#[cfg(feature = "server")]
pub mod representation;
#[cfg(feature = "server")]
pub mod filing;
#[cfg(feature = "server")]
pub mod service_record;
#[cfg(feature = "server")]
pub mod nef;
#[cfg(feature = "server")]
pub mod court_role_request;
#[cfg(feature = "server")]
pub mod charge;
#[cfg(feature = "server")]
pub mod defendant;
#[cfg(feature = "server")]
pub mod motion;
#[cfg(feature = "server")]
pub mod evidence;
#[cfg(feature = "server")]
pub mod custody_transfer;
#[cfg(feature = "server")]
pub mod case_note;
#[cfg(feature = "server")]
pub mod speedy_trial;
#[cfg(feature = "server")]
pub mod judge_conflict;
#[cfg(feature = "server")]
pub mod case_assignment;
#[cfg(feature = "server")]
pub mod recusal_motion;
#[cfg(feature = "server")]
pub mod order;
#[cfg(feature = "server")]
pub mod order_template;
#[cfg(feature = "server")]
pub mod opinion;
#[cfg(feature = "server")]
pub mod opinion_vote;
#[cfg(feature = "server")]
pub mod opinion_citation;
#[cfg(feature = "server")]
pub mod headnote;
#[cfg(feature = "server")]
pub mod opinion_draft;
#[cfg(feature = "server")]
pub mod draft_comment;
#[cfg(feature = "server")]
pub mod sentencing;
#[cfg(feature = "server")]
pub mod bar_admission;
#[cfg(feature = "server")]
pub mod federal_admission;
#[cfg(feature = "server")]
pub mod discipline;
#[cfg(feature = "server")]
pub mod pro_hac_vice;
#[cfg(feature = "server")]
pub mod cja_appointment;
#[cfg(feature = "server")]
pub mod ecf_registration;
#[cfg(feature = "server")]
pub mod sentencing_condition;
#[cfg(feature = "server")]
pub mod bop_designation;
#[cfg(feature = "server")]
pub mod prior_sentence;
#[cfg(feature = "server")]
pub mod extension_request;
#[cfg(feature = "server")]
pub mod deadline_reminder;
#[cfg(feature = "server")]
pub mod victim;
#[cfg(feature = "server")]
pub mod victim_notification;
#[cfg(feature = "server")]
pub mod config_override;
#[cfg(feature = "server")]
pub mod rule;
#[cfg(feature = "server")]
pub mod feature_flag;
#[cfg(feature = "server")]
pub mod conflict_check;
#[cfg(feature = "server")]
pub mod todo;
#[cfg(feature = "server")]
pub mod signature;
#[cfg(feature = "server")]
pub mod practice_area;
#[cfg(feature = "server")]
pub mod queue;
#[cfg(feature = "server")]
pub mod case_event;
#[cfg(feature = "server")]
pub mod fee_schedule;
